// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (used by Next.js and present in this repo), then fallback to .env
dotenv.config({ path: ".env.local" });
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma requires a datasource.url value at runtime; ensure we at least provide an empty string
    // so the config file contains the property. The CLI will still error if the DB URL is invalid.
    url: process.env["DATABASE_URL"],
  },
});
